# The first folder that contains all obsidian files
# Use full path or relative path, but don't use ~/
obsidian_folder_path_str: 'C:\farshid\farshid\Amazon Photos Downloads\Documents\tiziran.github.io' 

# The note that will be used as the index.html 
# should be in obsidian_folder_path_str
# Use full path or relative path, but don't use ~/
obsidian_entrypoint_path_str: 'C:\farshid\farshid\Amazon Photos Downloads\Documents\tiziran.github.io\test2.md'